-- MySQL Script generated by MySQL Workbench
-- 01/29/16 17:28:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema management
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `management` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `management` ;

-- -----------------------------------------------------
-- Table `management`.`thing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `management`.`thing` (
  `thing` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`thing`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `management`.`relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `management`.`relation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `management`.`property`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `management`.`property` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `thing` INT NOT NULL,
  `type` INT NOT NULL,
  `relation` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `property_thing_is_thing` (`thing` ASC),
  INDEX `property_type_is_thing` (`type` ASC),
  INDEX `property_relation_is_relation` (`relation` ASC),
  CONSTRAINT `property_thing_is_thing`
    FOREIGN KEY (`thing`)
    REFERENCES `management`.`thing` (`thing`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `property_type_is_thing`
    FOREIGN KEY (`type`)
    REFERENCES `management`.`thing` (`thing`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `property_relation_is_relation`
    FOREIGN KEY (`relation`)
    REFERENCES `management`.`relation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `management`.`management`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `management`.`management` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `management`.`instance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `management`.`instance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `management` INT NOT NULL,
  `thing` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `instance_management_is_management` (`management` ASC),
  INDEX `instance_thing_is_thing` (`thing` ASC),
  CONSTRAINT `instance_management_is_management`
    FOREIGN KEY (`management`)
    REFERENCES `management`.`management` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `instance_thing_is_thing`
    FOREIGN KEY (`thing`)
    REFERENCES `management`.`thing` (`thing`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `management`.`value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `management`.`value` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `instance` INT NOT NULL,
  `property` INT NOT NULL,
  `value` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `value_instance_is_instance` (`instance` ASC),
  INDEX `value_property_is_property` (`property` ASC),
  CONSTRAINT `value_instance_is_instance`
    FOREIGN KEY (`instance`)
    REFERENCES `management`.`instance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `value_property_is_property`
    FOREIGN KEY (`property`)
    REFERENCES `management`.`property` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
